// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApQbhVa7TzGb74LpjZSNZ01ysUkc64BWs',
    appId: '1:344461488497:web:59dba6d5650eb45ba046d0',
    messagingSenderId: '344461488497',
    projectId: 'flutter-ho-as',
    authDomain: 'flutter-ho-as.firebaseapp.com',
    storageBucket: 'flutter-ho-as.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqyDxiJoWxbbJ7LIY3_FObLUDe8f3nV5g',
    appId: '1:344461488497:android:5aaa34185e3479cda046d0',
    messagingSenderId: '344461488497',
    projectId: 'flutter-ho-as',
    storageBucket: 'flutter-ho-as.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACy9HicbnxUerdQUN0bXqmz23ROBcMsC0',
    appId: '1:344461488497:ios:92a3ad668f28004ca046d0',
    messagingSenderId: '344461488497',
    projectId: 'flutter-ho-as',
    storageBucket: 'flutter-ho-as.appspot.com',
    iosBundleId: 'com.example.flutterApplicationCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACy9HicbnxUerdQUN0bXqmz23ROBcMsC0',
    appId: '1:344461488497:ios:5491584069888599a046d0',
    messagingSenderId: '344461488497',
    projectId: 'flutter-ho-as',
    storageBucket: 'flutter-ho-as.appspot.com',
    iosBundleId: 'com.example.flutterApplicationCafe.RunnerTests',
  );
}
